### ISSUE TITLE
mate-applet-softupd (packagekit backend) checks for updates only after 10 min after startup

### ISSUE THREAD

**Issue by ronisbr** [assen-totin/mate-applet-softupd#2]
Hi!
I noticed that mate-applet-softupd checks for updates only after 10 min. after the startup (packagekit backend). This is probably due to `g_timeout_add`, because, as documentation says,

```
The first call to the function will be at the end of the first interval .
```

I am wondering if it is possible to modify the function so that the applet checks for update after its initialization.

**Comment by assen-totin** [comment]
Hi,

I'm not sure such modification is possible, but even more, I'm not sure it is useful at all. 

The reason for this is simple: the applet itself does not check for updates at any remote repository; it merely asks PackageKit whether there are any pending updates. PackageKit itself also does not check for updates at any remote repository, but rather checks with the local database if any update is pending. 

Updating the local database from remote repositories is usually done by a separate process, typically at boot time and then at some interval (you can trigger the same manually with commands like _yum check-update_ or _apt-get update_). The process of polling remote repositories takes some time, even if initiated on boot, so checking for updates immediately after applet starts makes little sense: even if there actually are updated packages in the remote repositories, the local database would not yet know about them. 10 minutes seems a reasonable interval to wait for the local database update process to do its work on boot and then the applet can report updates available.

WWell,

**Comment by ronisbr** [comment]
Hi @assen-totin,

This sounds reasonable to me.

Thanks,
Ronan
